### ISSUE TITLE
How to get DCGAN.npy,  DRAGAN.npy .... in Visualization.ipynb

### ISSUE THREAD

**Issue by Johnson-yue** [cc-hpc-itwm/UpConv#1]
Hi, I want to experiment with your repo  , I have trained with celeba dataset and LSGAN, but I have a question :

how to get "DCGAN.npy", "DRAGAN.npy", "LSGAN.npy" those data to show  in Visualization.ipynb???

**Comment by RicardDurall** [comment]
Hi,
you need to train the models (in this case DCGAN, DRAGN and LSGAN) and then, generate and save samples in a npy file. The shape of these files should be (B,C,H,W).

**Comment by keuperj** [comment]
How large are the models? can we provide them? Or the code to train them?

**Comment by RicardDurall** [comment]
The code to train them can be found in https://github.com/LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Pytorch mentioned on the main page under Training vanilla models.

**Comment by Johnson-yue** [comment]
@RicardDurall  I have trained some model , like LSGAN, WGAN-GP and so on. And I have a trained model weight, but I can not generate *.npy files , because I don't know what it is ,such storage format or number of samples.

Neither you nor LynnHo repo said how to generate *. npy files

Would you provide a code that how to use a trained model to generate *.npy files ?

**Comment by keuperj** [comment]
*.npy are the standard format to save numpy arrays to file. See

http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/generated/numpy.save.html

**Comment by Johnson-yue** [comment]
I know how to save numpy arrays to files. but don't know what to save @keuperj
