### ISSUE TITLE
Why is spectrum loss in the discriminator module?

### ISSUE THREAD

**Issue by lts129** [cc-hpc-itwm/UpConv#4]
The spectral loss should be related to the generator, however, it is written in the position of the discriminator in the program. The generator gradient is blocked with detach(), so the gradient of loss can only be fed back to the discriminator. However, there is nothing related to spectral loss in the discriminator. Could you tell me how the spectral loss actually works？

**Comment by Johnson-yue** [comment]
Maybe spectral loss is a kind of regularization for D ? like paper said ?

I still can not run Visualization.ipynb , because I don't know what the input npy data is

**Comment by RicardDurall** [comment]
The issue is now solved. There was a bug in the last update. Regarding the npy format, we just changed it to npz, so you should be able to visualize it.
