### ISSUE TITLE
Only three conv layer without activation functions?

### ISSUE THREAD

**Issue by Johnson-yue** [cc-hpc-itwm/UpConv#7]
https://github.com/cc-hpc-itwm/UpConv/blob/999b8569d830fce9b46d6f6e5e075e196e017d9c/Experiments_Codes/module_spectrum.py#L54-L57 

this part have no activation function,  maybe their function is the same  as one Conv layer??

**Comment by RicardDurall** [comment]
Hello,
we tried different configurations, and we found that this combination provides the best results. Please have a look at Figure 22 on our Supplemental Material.

**Comment by Johnson-yue** [comment]
ok, I see the Figure , but both of configuration have no activation, did you add Relu or something else after Conv layer for testing?

**Comment by RicardDurall** [comment]
We didnt add ReLu, but definitely it would make sense to test with it. However, what we observed is that having three conv was not the same as one, even though there was no activation. So we stuck to this configuration.

**Comment by Johnson-yue** [comment]
thank your reply , good answer!!! I will test it
