### ISSUE TITLE
G_loss is different from your paper

### ISSUE THREAD

**Issue by Johnson-yue** [cc-hpc-itwm/UpConv#8]
https://github.com/cc-hpc-itwm/UpConv/blob/999b8569d830fce9b46d6f6e5e075e196e017d9c/Experiments_Codes/train_spectrum.py#L166-L168

this code meaning the G_loss = g_loss + args.lambda_freq*loss_freq * g_loss
So finally :
`G_loss = g_loss *(1+ args.lambda_freq * loss_freq)`
Is the same as you paper ????:
`G_loss = g_loss + args.lambda_freq * loss_freq`

**Comment by RicardDurall** [comment]
Hello,
both expressions are equivalent. We could understand args.lambda_freq * loss_freq as a regularization term.

**Comment by Johnson-yue** [comment]
thank you
